[package]
name = "learning_rust"
version = "0.1.0"
authors = ["isakcodes <61279302+isakcodes@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
